name: Generate docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      - run: pip install mkdocs==1.0.4 mkdocs-material==4.6.0 Jinja2==3.0.3
      - run: mkdocs gh-deploy --force
